# Generated by Django 5.2.1 on 2025-06-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('external_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Imagem do Comentário')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='Vídeo do Comentário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='Imagem do Post')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Vídeo do Post')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
