# Generated by Django 5.2.1 on 2025-07-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
