# Generated by Django 5.2.1 on 2025-06-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
    ]
