# Generated by Django 5.2.1 on 2025-10-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
