# Generated by Django 5.2.1 on 2025-09-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_e_verificado_customuser_email_e_verificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_e_verificado',
            new_name='e_verificado',
        ),
    ]
