# Generated by Django 5.2.1 on 2025-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='capa',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='capas/', verbose_name='Capa'),
        ),
    ]
