# Generated by Django 5.1.2 on 2025-11-28 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome já existe.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='O nome de usuário pode conter letras, números, espaços e os caracteres @/./+/-/_', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
