# Generated by Django 5.2.7 on 2025-12-02 15:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='capa'),
        ),
    ]
