[project]
name = "comuna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.3",
    "django>=5.2.1",
    "pillow>=11.3.0",
    "psycopg[binary]>=3.2.11",
    "python-decouple>=3.8",
]
